### ISSUE TITLE
Request: upgrade Guzzle to 6.0

### ISSUE THREAD

**Issue by dvigueras** [abevallez/mountebank-php#3]
I wanted to use `mountebank-php` with Guzzle 6.0 but it requires Guzzle 5.3.

It would be awesome if you could release a new version supporting Guzzle 6.0, thanks!

**Comment by abrahamvallez** [comment]
I will try to release a new version as soon as possible. Feel free to collaborate if you feel it is necessary

**Comment by dvigueras** [comment]
Ok, thanks!
